services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 2s
      timeout: 2s
      retries: 15
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      OPENAI_API_KEY: "dummy"               # coloque a real se for usar as rotas /api/ai/*
      OPENAI_MODEL: "gpt-4o-mini"
      DATABASE_URL: "postgresql+psycopg2://app:app@db:5432/appdb"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://app:app@db:5432/appdb"
      GUNICORN_WORKERS: "1"
    ports:
      - "8080:5000"   # use 8080 no host pra não bater no AirPlay do macOS

volumes:
  pgdata: