"""init schema

Revision ID: 0001
Revises: 
Create Date: 2025-09-29 22:21:43.649320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty_factors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('fator_multiplicador_mao_obra', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel')
    )
    op.create_table('franchises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome_franquia', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('nome_franquia')
    )
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('custo_unitario_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_franqueado', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_franqueado'], ['franchises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('id_franquia', sa.String(length=36), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_franquia'], ['franchises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_franqueado', sa.String(length=36), nullable=False),
    sa.Column('id_cliente', sa.String(length=36), nullable=False),
    sa.Column('nome_projeto', sa.String(length=200), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('margem_lucro_aplicada', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('custo_total_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preco_venda_sugerido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['id_franqueado'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_projeto', sa.String(length=36), nullable=False),
    sa.Column('id_material', sa.String(length=36), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_dificuldade', sa.String(length=36), nullable=False),
    sa.Column('custo_item', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_venda_item', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_dificuldade'], ['difficulty_factors.id'], ),
    sa.ForeignKeyConstraint(['id_material'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['id_projeto'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_items')
    op.drop_table('projects')
    op.drop_table('user')
    op.drop_table('clients')
    op.drop_table('materials')
    op.drop_table('franchises')
    op.drop_table('difficulty_factors')
    # ### end Alembic commands ###
